/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 19/08/2021 07:50:17        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'D:\Bancos de Dados\POSTO.FDB'
USER 'SYSDBA' PASSWORD 'As#bank.'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GN_ABASTECIMENTOS START WITH 0 INCREMENT BY 1;
SET GENERATOR GN_ABASTECIMENTOS TO 0;

CREATE GENERATOR GN_BOMBAS START WITH 0 INCREMENT BY 1;
SET GENERATOR GN_BOMBAS TO 0;

CREATE GENERATOR GN_COMBUSTIVEIS START WITH 0 INCREMENT BY 1;
SET GENERATOR GN_COMBUSTIVEIS TO 0;

CREATE GENERATOR GN_TANQUES START WITH 0 INCREMENT BY 1;
SET GENERATOR GN_TANQUES TO 0;

CREATE GENERATOR GN_USUARIOS START WITH 0 INCREMENT BY 1;
SET GENERATOR GN_USUARIOS TO 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TB_ABASTECIMENTO (
    ID_ABASTECIMENTO  INTEGER NOT NULL,
    ID_BOMBA          INTEGER NOT NULL,
    ID_USUARIO        INTEGER NOT NULL,
    VALOR_LIQUIDO     NUMERIC(15,3) NOT NULL,
    LITROS            NUMERIC(15,3) NOT NULL,
    DATA              DATE NOT NULL,
    HORA              TIME NOT NULL,
    VALOR_IMPOSTO     NUMERIC(15,4) NOT NULL,
    VALOR_TOTAL       NUMERIC(15,4) NOT NULL
);

CREATE TABLE TB_BOMBAS (
    ID_BOMBA   INTEGER NOT NULL,
    NUMERO     INTEGER NOT NULL,
    ID_TANQUE  INTEGER NOT NULL
);

CREATE TABLE TB_COMBUSTIVEIS (
    ID_COMBUSTIVEL  INTEGER NOT NULL,
    TIPO            VARCHAR(60) NOT NULL,
    VALOR_COMPRA    NUMERIC(15,4) NOT NULL,
    VALOR_VENDA     NUMERIC(15,4) NOT NULL,
    PERC_IMPOSTO    NUMERIC(15,4) NOT NULL
);

CREATE TABLE TB_TANQUES (
    ID_TANQUE       INTEGER NOT NULL,
    NUMERO          INTEGER NOT NULL,
    ID_COMBUSTIVEL  INTEGER NOT NULL,
    CAPACIDADE      NUMERIC(15,4) NOT NULL
);

CREATE TABLE TB_USUARIOS (
    ID_USUARIO  INTEGER NOT NULL,
    NOME        VARCHAR(60) NOT NULL,
    USUARIO     VARCHAR(60) NOT NULL,
    SENHA       VARCHAR(60) NOT NULL,
    ATIVO       CHAR(1) DEFAULT 'S' NOT NULL
);



/******************************************************************************/
/****                          Unique constraints                          ****/
/******************************************************************************/

ALTER TABLE TB_BOMBAS ADD CONSTRAINT UNQ1_TB_BOMBAS UNIQUE (NUMERO);
ALTER TABLE TB_COMBUSTIVEIS ADD CONSTRAINT UNQ1_TB_COMBUSTIVEIS UNIQUE (TIPO);
ALTER TABLE TB_USUARIOS ADD CONSTRAINT UQ_TB_USUARIOS_USUARIO UNIQUE (USUARIO);


/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TB_ABASTECIMENTO ADD CONSTRAINT PK_TB_ABASTECIMENTO PRIMARY KEY (ID_ABASTECIMENTO);
ALTER TABLE TB_BOMBAS ADD CONSTRAINT PK_TB_BOMBAS PRIMARY KEY (ID_BOMBA);
ALTER TABLE TB_COMBUSTIVEIS ADD CONSTRAINT PK_TB_COMBUSTIVEIS PRIMARY KEY (ID_COMBUSTIVEL);
ALTER TABLE TB_TANQUES ADD CONSTRAINT PK_TB_TANQUES PRIMARY KEY (ID_TANQUE);
ALTER TABLE TB_USUARIOS ADD CONSTRAINT PK_TB_USUARIOS PRIMARY KEY (ID_USUARIO);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TB_ABASTECIMENTO ADD CONSTRAINT FK_TB_ABASTECIMENTO_1 FOREIGN KEY (ID_BOMBA) REFERENCES TB_BOMBAS (ID_BOMBA);
ALTER TABLE TB_ABASTECIMENTO ADD CONSTRAINT FK_TB_ABASTECIMENTO_2 FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS (ID_USUARIO);
ALTER TABLE TB_BOMBAS ADD CONSTRAINT FK_TB_BOMBAS_1 FOREIGN KEY (ID_TANQUE) REFERENCES TB_TANQUES (ID_TANQUE);
ALTER TABLE TB_TANQUES ADD CONSTRAINT FK_TB_TANQUES_1 FOREIGN KEY (ID_COMBUSTIVEL) REFERENCES TB_COMBUSTIVEIS (ID_COMBUSTIVEL);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: TB_ABASTECIMENTO_BI0 */
CREATE TRIGGER TB_ABASTECIMENTO_BI0 FOR TB_ABASTECIMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  /* Trigger text */
    If (new.id_abastecimento is null) then
        new.id_abastecimento = gen_id(gn_abastecimentos, 1);
end
^

/* Trigger: TB_BOMBAS_BI0 */
CREATE TRIGGER TB_BOMBAS_BI0 FOR TB_BOMBAS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  /* Trigger text */
    If (new.id_bomba is null) then
        new.id_bomba = gen_id(gn_bombas, 1);
end
^

/* Trigger: TB_COMBUSTIVEIS_BI0 */
CREATE TRIGGER TB_COMBUSTIVEIS_BI0 FOR TB_COMBUSTIVEIS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  /* Trigger text */
    If (new.id_combustivel is null) then
        new.id_combustivel = gen_id(gn_combustiveis, 1);
end
^

/* Trigger: TB_TANQUES_BI0 */
CREATE TRIGGER TB_TANQUES_BI0 FOR TB_TANQUES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  /* Trigger text */
    If (new.id_tanque is null) then
        new.id_tanque = gen_id(gn_tanques, 1);
end
^

/* Trigger: TB_USUARIOS_BI0 */
CREATE TRIGGER TB_USUARIOS_BI0 FOR TB_USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  /* Trigger text */
    If (new.id_usuario is null) then
        new.id_usuario = gen_id(gn_usuarios, 1);
end
^
SET TERM ; ^

